### PR TITLE
FIX: remove heavy-weight example files

### PR DESCRIPTION
**Pull request by mckib2**
- reduces PROPACK submodule size to ~2MB instead of ~150 MB
- xref https://github.com/MacPython/scipy-wheels/issues/154

I have not evaluated the changes this will have to the `scipy.sparse.linalg.svds` test suite, I suspect there will need to be some adjustments.  This PR is only to suggest one proposed approach for dealing with the PROPACK-size problem

### CODE REVIEW

**Comment by mdhaber** [comment]
This is fine if it's what we need to do. Yes, we'd need to change `/scipy/sparse/linalg/tests/test_propack::test_examples` to load the data from a new NPZ or something. @rgommers please confirm and we'll pull the trigger.

**Review by mdhaber — APPROVED** [review]

**Comment by mckib2** [comment]
A couple other options (just to try to be complete and thoughtful):
- create a "release" branch and a "testing" branch.  The "release" branch would exclude large example files and be used by the source distribution and wheel providers.  The "testing" branch would be checked out in our CI and could include all the large files necessary
- store large files somewhere else and download them for testing only (might require someone to donate server space for us)

I'm also good with simply removing per this PR and then when updating the commit hash for PROPACK in SciPy-proper, add required data for the test @mdhaber pointed out above

**Comment by rgommers** [comment]
+1 for just removing, and only keeping `.npz` files if needed for testing. These examples will never be modified anymore upstream, and anyway keeping numerical data in ascii files isn't a useful thing to do.

**Comment by mdhaber** [comment]
What size do you want the `.npz` files to be? 

- Converted to `npz` format, all the files are 37 MB. 
- Storing everything in the same file and eliminating some redundancy, we can store the same data in half that space. 
- Currently, we are storing both example matrices and a reference SVD provided with PROPACK. If we need to save more space, we can store the example matrices in only 587 KB and compare against a reference SVD computed with `linalg.svd`.
- We could just generate random matrices and store nothing.

**Comment by rgommers** [comment]
> * Converted to `npz` format, all the files are 37 MB.

That much still? I thought I had in a comment on the original PR that it'd be 2 MB. That would be acceptable (perhaps, just), I think 37 MB is way too much.

> * If we need to save more space, we can store the example matrices in only 587 KB and compare against a reference SVD computed with `linalg.svd`.

That sounds reasonable. I'm happy with either this approach or just using random matrices - whichever you prefer.

**Comment by mdhaber** [comment]
I see at the top of this PR is that the PROPACK submodule would be 2MB after removing all the example files.
But I don't think the full examples can be compressed that much automatically. The output includes many dense matrices, each with 256k elements.
I'll go the 587 KB route.

**Comment by mckib2** [comment]
> That much still? I thought I had in a comment on the original PR that it'd be 2 MB. That would be acceptable (perhaps, just), I think 37 MB is way too much.

@mdhaber was correct -- 2 MB without any examples or npz files

Looks like this is a good solution -- remove the files from here and add a reduced npz file to main scipy repo.  I'd feel weird about creating a PR and then completing it myself, so I invite either of you @rgommers @mdhaber to complete if you're happy

**Comment by mdhaber** [comment]
I will, but I think we should merge scipy/scipy#15214 first so that there is no lapse in tests working

**Comment by mdhaber** [comment]
Oh, sounds like we need to update a commit hash, so there's no lapse even if we merge this first?

**Comment by mckib2** [comment]
> Oh, sounds like we need to update a commit hash, so there's no lapse even if we merge this first?

Correct, we need to explicitly commit a new hash in the parent SciPy repo for any changes here to take effect

**Pull request merged**
