### PR TITLE
Remove all timer related code

### PR DESCRIPTION
**Pull request by rgommers**
Using `second` is problematic: it causes build issues because ETIME is a GNU extension, and things currently don't build with Intel Fortran for example. Timing inside Fortran code is also not at all useful for SciPy.

After this is merged, I'll open a SciPy PR to remove the usage of `second.F` from `meson.build` and `setup.py`. EDIT: already tested that that works locally with these changes.

### CODE REVIEW

**Comment by ev-br** [comment]
LGTM thanks Ralf

**Comment by ilayn** [comment]
Looks like this is a repo branch @rgommers fyi

**Comment by rgommers** [comment]
> Looks like this is a repo branch @rgommers fyi

Yes I know, sorry - was a bit lazy (didn't have a fork yet and was in a hurry) - it's gone now.

**Comment by ilayn** [comment]
No worries just a reminder.

**Pull request merged**
